name: Update Submodules Daily

on:
  schedule:
    # Runs at 5:30 PM IST (12:00 UTC)
    - cron: '30 12 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{vars.CHORE_APP_ID}}
          private-key: ${{secrets.CHORE_ACCOUNT_TOKEN}}
          owner: ${{ github.repository_owner }}
          repositories: |
            adityais.dev
            adityais.dev-content

      - name: Update submodules
        run: |
          git config --global user.name 'Chore Bot'
          git config --global user.email '${{vars.CHORE_APP_ID}}+as1100k-chore[bot]@users.noreply.github.com'
          git submodule update --remote --recursive
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
            git commit -m "chore: update submodules [no ci]"
            git push
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}