name: Update Submodules Daily

on:
  schedule:
    # Runs at 6:00 PM IST (12:00 UTC)
    - cron: '30 12 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Generate GitHub App token
        uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{vars.CHORE_APP_ID}}
          private-key: ${{secrets.CHORE_ACCOUNT_TOKEN}}
          owner: ${{ github.repository_owner }}
          repositories: |
            adityais.dev
            adityais.dev-content

      - uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{steps.app-token.outputs.token}}

      - name: Get GitHub App User ID
        id: get-user-id
        run: echo "user-id=$(gh api "/users/${{ steps.app-token.outputs.app-slug }}[bot]" --jq .id)" >> "$GITHUB_OUTPUT"
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
      
      - name: Config Git
        run: |
          git config --global user.name '${{ steps.app-token.outputs.app-slug }}[bot]'
          git config --global user.email '${{ steps.get-user-id.outputs.user-id }}+${{ steps.app-token.outputs.app-slug }}[bot]@users.noreply.github.com'

      - name: Update submodules
        run: |
          git submodule update --remote --recursive
          git add .
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          fi
            git commit -m "chore: update submodules [no ci]"
            git push
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}