name: CI

on:
  push:
    branches: [main]
    paths:
      - "tools/**.rs"
      - "tools/**.toml"
  pull_request:
    branches: [main]
    paths:
      - "tools/**.rs"
      - "tools/**.toml"

env:
  CARGO_TERM_COLOR: always

jobs:
  # Run cargo test
  test:
    name: Test Suite
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: rs-workspace/rust-toolchain@v0.2.0
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run cargo test
        run: cd tools && cargo test --workspace --all-features

  # Run cargo clippy
  clippy_check:
    name: Clippy
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: rs-workspace/rust-toolchain@v0.2.0
      - name: Install Dependencies
        run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev libudev-dev
      - name: Run clippy
        run: cd tools && cargo clippy --workspace --all-features -- -Dwarnings

  # Run cargo fmt --all -- --check
  format:
    name: Format
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Install stable toolchain
        uses: rs-workspace/rust-toolchain@v0.2.0
      - name: Run cargo fmt
        run: cd tools && cargo fmt --all -- --check
